# Changes here will be overwritten by Copier
_commit: v0.1.5
_src_path: gh:ninanor/python-template
author_name: Francesco Frassinelli
debug: false
default_branch_name: main
docker: false
email: francesco.frassinelli@nina.no
notebook: false
project_name: artsobservasjoner download
project_slug: artsobservasjoner_download
repo_name: artsobservasjoner_download
repo_org: ninanor
template_type: python
type_annotations: false
